# Generated by Django 2.1.2 on 2018-11-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('des', models.CharField(max_length=240)),
                ('badge', models.CharField(max_length=10)),
                ('chunk', models.TextField(max_length=2000)),
            ],
        ),
    ]
