# Generated by Django 2.1.2 on 2018-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkmodel',
            name='lang',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
