# Generated by Django 2.1.2 on 2018-11-08 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_chunkmodel_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='chunkmodel',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_page.Badge'),
        ),
    ]
