# Generated by Django 2.1.2 on 2018-11-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_auto_20181108_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('badge', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='chunkmodel',
            name='badge',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='index_page.Badge'),
        ),
        migrations.AlterField(
            model_name='chunkmodel',
            name='chunk',
            field=models.TextField(max_length=10000),
        ),
    ]
