# Generated by Django 2.1.2 on 2018-11-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0004_auto_20181110_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkmodel',
            name='lang',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='index_page.Language'),
        ),
    ]
