# Generated by Django 2.1.2 on 2018-11-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0005_auto_20181110_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='badge',
            new_name='abb',
        ),
        migrations.RemoveField(
            model_name='chunkmodel',
            name='badge',
        ),
    ]
